#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18408
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PddAndroid.Resource", IsApplication=true)]

namespace PddAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int blank = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int pdd_01_02 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int pdd_01_03 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int pdd_01_04 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int pdd_01_05 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int pdd_01_07 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int pdd_01_08 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int pdd_01_09 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int pdd_01_10 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int pdd_01_11 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int pdd_01_12 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int pdd_01_13 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int pdd_01_14 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int pdd_01_15 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int pdd_01_16 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int pdd_02_02 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int pdd_02_03 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int pdd_02_04 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int pdd_02_05 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int pdd_02_06 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int pdd_02_07 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int pdd_02_08 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int pdd_02_09 = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int pdd_02_11 = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int pdd_02_12 = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int pdd_02_13 = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int pdd_02_14 = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int pdd_02_15 = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int pdd_02_16 = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int pdd_03_01 = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int pdd_03_02 = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int pdd_03_03 = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int pdd_03_04 = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int pdd_03_05 = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int pdd_03_06 = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int pdd_03_08 = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int pdd_03_09 = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int pdd_03_10 = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int pdd_03_12 = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int pdd_03_13 = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int pdd_03_14 = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int pdd_03_15 = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int pdd_03_16 = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int pdd_04_01 = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int pdd_04_02 = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int pdd_04_03 = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int pdd_04_04 = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int pdd_04_06 = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int pdd_04_07 = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int pdd_04_08 = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int pdd_04_09 = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int pdd_04_11 = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int pdd_04_12 = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int pdd_04_13 = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int pdd_04_14 = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int pdd_04_15 = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int pdd_05_01 = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int pdd_05_02 = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int pdd_05_03 = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int pdd_05_04 = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int pdd_05_05 = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int pdd_05_07 = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int pdd_05_08 = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int pdd_05_09 = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int pdd_05_10 = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int pdd_05_11 = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int pdd_05_12 = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int pdd_05_13 = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int pdd_05_14 = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int pdd_05_15 = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int pdd_05_16 = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int pdd_05_20 = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int pdd_06_02 = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int pdd_06_03 = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int pdd_06_04 = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int pdd_06_05 = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int pdd_06_07 = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int pdd_06_08 = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int pdd_06_09 = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int pdd_06_10 = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int pdd_06_11 = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int pdd_06_12 = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int pdd_06_13 = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int pdd_06_14 = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int pdd_06_15 = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int pdd_06_19 = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int pdd_07_02 = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int pdd_07_03 = 2130837592;
			
			// aapt resource value: 0x7f020059
			public const int pdd_07_04 = 2130837593;
			
			// aapt resource value: 0x7f02005a
			public const int pdd_07_05 = 2130837594;
			
			// aapt resource value: 0x7f02005b
			public const int pdd_07_06 = 2130837595;
			
			// aapt resource value: 0x7f02005c
			public const int pdd_07_08 = 2130837596;
			
			// aapt resource value: 0x7f02005d
			public const int pdd_07_09 = 2130837597;
			
			// aapt resource value: 0x7f02005e
			public const int pdd_07_10 = 2130837598;
			
			// aapt resource value: 0x7f02005f
			public const int pdd_07_11 = 2130837599;
			
			// aapt resource value: 0x7f020060
			public const int pdd_07_12 = 2130837600;
			
			// aapt resource value: 0x7f020061
			public const int pdd_07_13 = 2130837601;
			
			// aapt resource value: 0x7f020062
			public const int pdd_07_14 = 2130837602;
			
			// aapt resource value: 0x7f020063
			public const int pdd_07_15 = 2130837603;
			
			// aapt resource value: 0x7f020064
			public const int pdd_07_17 = 2130837604;
			
			// aapt resource value: 0x7f020065
			public const int pdd_08_02 = 2130837605;
			
			// aapt resource value: 0x7f020066
			public const int pdd_08_03 = 2130837606;
			
			// aapt resource value: 0x7f020067
			public const int pdd_08_04 = 2130837607;
			
			// aapt resource value: 0x7f020068
			public const int pdd_08_05 = 2130837608;
			
			// aapt resource value: 0x7f020069
			public const int pdd_08_06 = 2130837609;
			
			// aapt resource value: 0x7f02006a
			public const int pdd_08_07 = 2130837610;
			
			// aapt resource value: 0x7f02006b
			public const int pdd_08_08 = 2130837611;
			
			// aapt resource value: 0x7f02006c
			public const int pdd_08_10 = 2130837612;
			
			// aapt resource value: 0x7f02006d
			public const int pdd_08_11 = 2130837613;
			
			// aapt resource value: 0x7f02006e
			public const int pdd_08_12 = 2130837614;
			
			// aapt resource value: 0x7f02006f
			public const int pdd_08_13 = 2130837615;
			
			// aapt resource value: 0x7f020070
			public const int pdd_08_14 = 2130837616;
			
			// aapt resource value: 0x7f020071
			public const int pdd_08_15 = 2130837617;
			
			// aapt resource value: 0x7f020072
			public const int pdd_08_16 = 2130837618;
			
			// aapt resource value: 0x7f020073
			public const int pdd_09_02 = 2130837619;
			
			// aapt resource value: 0x7f020074
			public const int pdd_09_03 = 2130837620;
			
			// aapt resource value: 0x7f020075
			public const int pdd_09_04 = 2130837621;
			
			// aapt resource value: 0x7f020076
			public const int pdd_09_05 = 2130837622;
			
			// aapt resource value: 0x7f020077
			public const int pdd_09_06 = 2130837623;
			
			// aapt resource value: 0x7f020078
			public const int pdd_09_08 = 2130837624;
			
			// aapt resource value: 0x7f020079
			public const int pdd_09_09 = 2130837625;
			
			// aapt resource value: 0x7f02007a
			public const int pdd_09_10 = 2130837626;
			
			// aapt resource value: 0x7f02007b
			public const int pdd_09_11 = 2130837627;
			
			// aapt resource value: 0x7f02007c
			public const int pdd_09_12 = 2130837628;
			
			// aapt resource value: 0x7f02007d
			public const int pdd_09_13 = 2130837629;
			
			// aapt resource value: 0x7f02007e
			public const int pdd_09_14 = 2130837630;
			
			// aapt resource value: 0x7f02007f
			public const int pdd_09_15 = 2130837631;
			
			// aapt resource value: 0x7f020080
			public const int pdd_09_19 = 2130837632;
			
			// aapt resource value: 0x7f020081
			public const int pdd_10_01 = 2130837633;
			
			// aapt resource value: 0x7f020082
			public const int pdd_10_02 = 2130837634;
			
			// aapt resource value: 0x7f020083
			public const int pdd_10_03 = 2130837635;
			
			// aapt resource value: 0x7f020084
			public const int pdd_10_04 = 2130837636;
			
			// aapt resource value: 0x7f020085
			public const int pdd_10_05 = 2130837637;
			
			// aapt resource value: 0x7f020086
			public const int pdd_10_06 = 2130837638;
			
			// aapt resource value: 0x7f020087
			public const int pdd_10_07 = 2130837639;
			
			// aapt resource value: 0x7f020088
			public const int pdd_10_08 = 2130837640;
			
			// aapt resource value: 0x7f020089
			public const int pdd_10_09 = 2130837641;
			
			// aapt resource value: 0x7f02008a
			public const int pdd_10_11 = 2130837642;
			
			// aapt resource value: 0x7f02008b
			public const int pdd_10_13 = 2130837643;
			
			// aapt resource value: 0x7f02008c
			public const int pdd_10_14 = 2130837644;
			
			// aapt resource value: 0x7f02008d
			public const int pdd_10_15 = 2130837645;
			
			// aapt resource value: 0x7f02008e
			public const int pdd_10_16 = 2130837646;
			
			// aapt resource value: 0x7f02008f
			public const int pdd_11_02 = 2130837647;
			
			// aapt resource value: 0x7f020090
			public const int pdd_11_03 = 2130837648;
			
			// aapt resource value: 0x7f020091
			public const int pdd_11_04 = 2130837649;
			
			// aapt resource value: 0x7f020092
			public const int pdd_11_05 = 2130837650;
			
			// aapt resource value: 0x7f020093
			public const int pdd_11_07 = 2130837651;
			
			// aapt resource value: 0x7f020094
			public const int pdd_11_08 = 2130837652;
			
			// aapt resource value: 0x7f020095
			public const int pdd_11_09 = 2130837653;
			
			// aapt resource value: 0x7f020096
			public const int pdd_11_12 = 2130837654;
			
			// aapt resource value: 0x7f020097
			public const int pdd_11_13 = 2130837655;
			
			// aapt resource value: 0x7f020098
			public const int pdd_11_14 = 2130837656;
			
			// aapt resource value: 0x7f020099
			public const int pdd_11_15 = 2130837657;
			
			// aapt resource value: 0x7f02009a
			public const int pdd_11_16 = 2130837658;
			
			// aapt resource value: 0x7f02009b
			public const int pdd_11_19 = 2130837659;
			
			// aapt resource value: 0x7f02009c
			public const int pdd_12_02 = 2130837660;
			
			// aapt resource value: 0x7f02009d
			public const int pdd_12_03 = 2130837661;
			
			// aapt resource value: 0x7f02009e
			public const int pdd_12_04 = 2130837662;
			
			// aapt resource value: 0x7f02009f
			public const int pdd_12_05 = 2130837663;
			
			// aapt resource value: 0x7f0200a0
			public const int pdd_12_06 = 2130837664;
			
			// aapt resource value: 0x7f0200a1
			public const int pdd_12_07 = 2130837665;
			
			// aapt resource value: 0x7f0200a2
			public const int pdd_12_08 = 2130837666;
			
			// aapt resource value: 0x7f0200a3
			public const int pdd_12_09 = 2130837667;
			
			// aapt resource value: 0x7f0200a4
			public const int pdd_12_10 = 2130837668;
			
			// aapt resource value: 0x7f0200a5
			public const int pdd_12_11 = 2130837669;
			
			// aapt resource value: 0x7f0200a6
			public const int pdd_12_12 = 2130837670;
			
			// aapt resource value: 0x7f0200a7
			public const int pdd_12_13 = 2130837671;
			
			// aapt resource value: 0x7f0200a8
			public const int pdd_12_14 = 2130837672;
			
			// aapt resource value: 0x7f0200a9
			public const int pdd_12_15 = 2130837673;
			
			// aapt resource value: 0x7f0200aa
			public const int pdd_12_19 = 2130837674;
			
			// aapt resource value: 0x7f0200ab
			public const int pdd_13_01 = 2130837675;
			
			// aapt resource value: 0x7f0200ac
			public const int pdd_13_02 = 2130837676;
			
			// aapt resource value: 0x7f0200ad
			public const int pdd_13_03 = 2130837677;
			
			// aapt resource value: 0x7f0200ae
			public const int pdd_13_04 = 2130837678;
			
			// aapt resource value: 0x7f0200af
			public const int pdd_13_05 = 2130837679;
			
			// aapt resource value: 0x7f0200b0
			public const int pdd_13_06 = 2130837680;
			
			// aapt resource value: 0x7f0200b1
			public const int pdd_13_08 = 2130837681;
			
			// aapt resource value: 0x7f0200b2
			public const int pdd_13_09 = 2130837682;
			
			// aapt resource value: 0x7f0200b3
			public const int pdd_13_10 = 2130837683;
			
			// aapt resource value: 0x7f0200b4
			public const int pdd_13_11 = 2130837684;
			
			// aapt resource value: 0x7f0200b5
			public const int pdd_13_12 = 2130837685;
			
			// aapt resource value: 0x7f0200b6
			public const int pdd_13_13 = 2130837686;
			
			// aapt resource value: 0x7f0200b7
			public const int pdd_13_14 = 2130837687;
			
			// aapt resource value: 0x7f0200b8
			public const int pdd_13_15 = 2130837688;
			
			// aapt resource value: 0x7f0200b9
			public const int pdd_13_16 = 2130837689;
			
			// aapt resource value: 0x7f0200ba
			public const int pdd_14_02 = 2130837690;
			
			// aapt resource value: 0x7f0200bb
			public const int pdd_14_03 = 2130837691;
			
			// aapt resource value: 0x7f0200bc
			public const int pdd_14_04 = 2130837692;
			
			// aapt resource value: 0x7f0200bd
			public const int pdd_14_05 = 2130837693;
			
			// aapt resource value: 0x7f0200be
			public const int pdd_14_06 = 2130837694;
			
			// aapt resource value: 0x7f0200bf
			public const int pdd_14_07 = 2130837695;
			
			// aapt resource value: 0x7f0200c0
			public const int pdd_14_08 = 2130837696;
			
			// aapt resource value: 0x7f0200c1
			public const int pdd_14_09 = 2130837697;
			
			// aapt resource value: 0x7f0200c2
			public const int pdd_14_11 = 2130837698;
			
			// aapt resource value: 0x7f0200c3
			public const int pdd_14_12 = 2130837699;
			
			// aapt resource value: 0x7f0200c4
			public const int pdd_14_13 = 2130837700;
			
			// aapt resource value: 0x7f0200c5
			public const int pdd_14_14 = 2130837701;
			
			// aapt resource value: 0x7f0200c6
			public const int pdd_14_15 = 2130837702;
			
			// aapt resource value: 0x7f0200c7
			public const int pdd_14_16 = 2130837703;
			
			// aapt resource value: 0x7f0200c8
			public const int pdd_15_02 = 2130837704;
			
			// aapt resource value: 0x7f0200c9
			public const int pdd_15_03 = 2130837705;
			
			// aapt resource value: 0x7f0200ca
			public const int pdd_15_04 = 2130837706;
			
			// aapt resource value: 0x7f0200cb
			public const int pdd_15_05 = 2130837707;
			
			// aapt resource value: 0x7f0200cc
			public const int pdd_15_06 = 2130837708;
			
			// aapt resource value: 0x7f0200cd
			public const int pdd_15_07 = 2130837709;
			
			// aapt resource value: 0x7f0200ce
			public const int pdd_15_08 = 2130837710;
			
			// aapt resource value: 0x7f0200cf
			public const int pdd_15_09 = 2130837711;
			
			// aapt resource value: 0x7f0200d0
			public const int pdd_15_12 = 2130837712;
			
			// aapt resource value: 0x7f0200d1
			public const int pdd_15_13 = 2130837713;
			
			// aapt resource value: 0x7f0200d2
			public const int pdd_15_14 = 2130837714;
			
			// aapt resource value: 0x7f0200d3
			public const int pdd_15_15 = 2130837715;
			
			// aapt resource value: 0x7f0200d4
			public const int pdd_15_16 = 2130837716;
			
			// aapt resource value: 0x7f0200d5
			public const int pdd_16_02 = 2130837717;
			
			// aapt resource value: 0x7f0200d6
			public const int pdd_16_03 = 2130837718;
			
			// aapt resource value: 0x7f0200d7
			public const int pdd_16_04 = 2130837719;
			
			// aapt resource value: 0x7f0200d8
			public const int pdd_16_05 = 2130837720;
			
			// aapt resource value: 0x7f0200d9
			public const int pdd_16_06 = 2130837721;
			
			// aapt resource value: 0x7f0200da
			public const int pdd_16_08 = 2130837722;
			
			// aapt resource value: 0x7f0200db
			public const int pdd_16_09 = 2130837723;
			
			// aapt resource value: 0x7f0200dc
			public const int pdd_16_10 = 2130837724;
			
			// aapt resource value: 0x7f0200dd
			public const int pdd_16_11 = 2130837725;
			
			// aapt resource value: 0x7f0200de
			public const int pdd_16_12 = 2130837726;
			
			// aapt resource value: 0x7f0200df
			public const int pdd_16_13 = 2130837727;
			
			// aapt resource value: 0x7f0200e0
			public const int pdd_16_14 = 2130837728;
			
			// aapt resource value: 0x7f0200e1
			public const int pdd_16_15 = 2130837729;
			
			// aapt resource value: 0x7f0200e2
			public const int pdd_16_16 = 2130837730;
			
			// aapt resource value: 0x7f0200e3
			public const int pdd_16_19 = 2130837731;
			
			// aapt resource value: 0x7f0200e4
			public const int pdd_17_02 = 2130837732;
			
			// aapt resource value: 0x7f0200e5
			public const int pdd_17_03 = 2130837733;
			
			// aapt resource value: 0x7f0200e6
			public const int pdd_17_04 = 2130837734;
			
			// aapt resource value: 0x7f0200e7
			public const int pdd_17_05 = 2130837735;
			
			// aapt resource value: 0x7f0200e8
			public const int pdd_17_06 = 2130837736;
			
			// aapt resource value: 0x7f0200e9
			public const int pdd_17_07 = 2130837737;
			
			// aapt resource value: 0x7f0200ea
			public const int pdd_17_08 = 2130837738;
			
			// aapt resource value: 0x7f0200eb
			public const int pdd_17_09 = 2130837739;
			
			// aapt resource value: 0x7f0200ec
			public const int pdd_17_11 = 2130837740;
			
			// aapt resource value: 0x7f0200ed
			public const int pdd_17_12 = 2130837741;
			
			// aapt resource value: 0x7f0200ee
			public const int pdd_17_13 = 2130837742;
			
			// aapt resource value: 0x7f0200ef
			public const int pdd_17_14 = 2130837743;
			
			// aapt resource value: 0x7f0200f0
			public const int pdd_17_15 = 2130837744;
			
			// aapt resource value: 0x7f0200f1
			public const int pdd_17_16 = 2130837745;
			
			// aapt resource value: 0x7f0200f2
			public const int pdd_18_02 = 2130837746;
			
			// aapt resource value: 0x7f0200f3
			public const int pdd_18_03 = 2130837747;
			
			// aapt resource value: 0x7f0200f4
			public const int pdd_18_04 = 2130837748;
			
			// aapt resource value: 0x7f0200f5
			public const int pdd_18_05 = 2130837749;
			
			// aapt resource value: 0x7f0200f6
			public const int pdd_18_06 = 2130837750;
			
			// aapt resource value: 0x7f0200f7
			public const int pdd_18_07 = 2130837751;
			
			// aapt resource value: 0x7f0200f8
			public const int pdd_18_08 = 2130837752;
			
			// aapt resource value: 0x7f0200f9
			public const int pdd_18_10 = 2130837753;
			
			// aapt resource value: 0x7f0200fa
			public const int pdd_18_11 = 2130837754;
			
			// aapt resource value: 0x7f0200fb
			public const int pdd_18_12 = 2130837755;
			
			// aapt resource value: 0x7f0200fc
			public const int pdd_18_13 = 2130837756;
			
			// aapt resource value: 0x7f0200fd
			public const int pdd_18_14 = 2130837757;
			
			// aapt resource value: 0x7f0200fe
			public const int pdd_18_15 = 2130837758;
			
			// aapt resource value: 0x7f0200ff
			public const int pdd_18_16 = 2130837759;
			
			// aapt resource value: 0x7f020100
			public const int pdd_19_01 = 2130837760;
			
			// aapt resource value: 0x7f020101
			public const int pdd_19_02 = 2130837761;
			
			// aapt resource value: 0x7f020102
			public const int pdd_19_03 = 2130837762;
			
			// aapt resource value: 0x7f020103
			public const int pdd_19_04 = 2130837763;
			
			// aapt resource value: 0x7f020104
			public const int pdd_19_06 = 2130837764;
			
			// aapt resource value: 0x7f020105
			public const int pdd_19_08 = 2130837765;
			
			// aapt resource value: 0x7f020106
			public const int pdd_19_09 = 2130837766;
			
			// aapt resource value: 0x7f020107
			public const int pdd_19_10 = 2130837767;
			
			// aapt resource value: 0x7f020108
			public const int pdd_19_11 = 2130837768;
			
			// aapt resource value: 0x7f020109
			public const int pdd_19_12 = 2130837769;
			
			// aapt resource value: 0x7f02010a
			public const int pdd_19_13 = 2130837770;
			
			// aapt resource value: 0x7f02010b
			public const int pdd_19_14 = 2130837771;
			
			// aapt resource value: 0x7f02010c
			public const int pdd_19_15 = 2130837772;
			
			// aapt resource value: 0x7f02010d
			public const int pdd_19_16 = 2130837773;
			
			// aapt resource value: 0x7f02010e
			public const int pdd_20_01 = 2130837774;
			
			// aapt resource value: 0x7f02010f
			public const int pdd_20_02 = 2130837775;
			
			// aapt resource value: 0x7f020110
			public const int pdd_20_03 = 2130837776;
			
			// aapt resource value: 0x7f020111
			public const int pdd_20_04 = 2130837777;
			
			// aapt resource value: 0x7f020112
			public const int pdd_20_06 = 2130837778;
			
			// aapt resource value: 0x7f020113
			public const int pdd_20_07 = 2130837779;
			
			// aapt resource value: 0x7f020114
			public const int pdd_20_08 = 2130837780;
			
			// aapt resource value: 0x7f020115
			public const int pdd_20_09 = 2130837781;
			
			// aapt resource value: 0x7f020116
			public const int pdd_20_10 = 2130837782;
			
			// aapt resource value: 0x7f020117
			public const int pdd_20_11 = 2130837783;
			
			// aapt resource value: 0x7f020118
			public const int pdd_20_12 = 2130837784;
			
			// aapt resource value: 0x7f020119
			public const int pdd_20_13 = 2130837785;
			
			// aapt resource value: 0x7f02011a
			public const int pdd_20_14 = 2130837786;
			
			// aapt resource value: 0x7f02011b
			public const int pdd_20_15 = 2130837787;
			
			// aapt resource value: 0x7f02011c
			public const int pdd_20_16 = 2130837788;
			
			// aapt resource value: 0x7f02011d
			public const int pdd_20_18 = 2130837789;
			
			// aapt resource value: 0x7f02011e
			public const int pdd_21_02 = 2130837790;
			
			// aapt resource value: 0x7f02011f
			public const int pdd_21_03 = 2130837791;
			
			// aapt resource value: 0x7f020120
			public const int pdd_21_04 = 2130837792;
			
			// aapt resource value: 0x7f020121
			public const int pdd_21_05 = 2130837793;
			
			// aapt resource value: 0x7f020122
			public const int pdd_21_06 = 2130837794;
			
			// aapt resource value: 0x7f020123
			public const int pdd_21_07 = 2130837795;
			
			// aapt resource value: 0x7f020124
			public const int pdd_21_08 = 2130837796;
			
			// aapt resource value: 0x7f020125
			public const int pdd_21_10 = 2130837797;
			
			// aapt resource value: 0x7f020126
			public const int pdd_21_11 = 2130837798;
			
			// aapt resource value: 0x7f020127
			public const int pdd_21_12 = 2130837799;
			
			// aapt resource value: 0x7f020128
			public const int pdd_21_13 = 2130837800;
			
			// aapt resource value: 0x7f020129
			public const int pdd_21_14 = 2130837801;
			
			// aapt resource value: 0x7f02012a
			public const int pdd_21_15 = 2130837802;
			
			// aapt resource value: 0x7f02012b
			public const int pdd_21_17 = 2130837803;
			
			// aapt resource value: 0x7f02012c
			public const int pdd_21_19 = 2130837804;
			
			// aapt resource value: 0x7f02012d
			public const int pdd_22_01 = 2130837805;
			
			// aapt resource value: 0x7f02012e
			public const int pdd_22_02 = 2130837806;
			
			// aapt resource value: 0x7f02012f
			public const int pdd_22_03 = 2130837807;
			
			// aapt resource value: 0x7f020130
			public const int pdd_22_05 = 2130837808;
			
			// aapt resource value: 0x7f020131
			public const int pdd_22_06 = 2130837809;
			
			// aapt resource value: 0x7f020132
			public const int pdd_22_07 = 2130837810;
			
			// aapt resource value: 0x7f020133
			public const int pdd_22_08 = 2130837811;
			
			// aapt resource value: 0x7f020134
			public const int pdd_22_09 = 2130837812;
			
			// aapt resource value: 0x7f020135
			public const int pdd_22_12 = 2130837813;
			
			// aapt resource value: 0x7f020136
			public const int pdd_22_13 = 2130837814;
			
			// aapt resource value: 0x7f020137
			public const int pdd_22_14 = 2130837815;
			
			// aapt resource value: 0x7f020138
			public const int pdd_22_15 = 2130837816;
			
			// aapt resource value: 0x7f020139
			public const int pdd_22_16 = 2130837817;
			
			// aapt resource value: 0x7f02013a
			public const int pdd_23_01 = 2130837818;
			
			// aapt resource value: 0x7f02013b
			public const int pdd_23_02 = 2130837819;
			
			// aapt resource value: 0x7f02013c
			public const int pdd_23_03 = 2130837820;
			
			// aapt resource value: 0x7f02013d
			public const int pdd_23_04 = 2130837821;
			
			// aapt resource value: 0x7f02013e
			public const int pdd_23_05 = 2130837822;
			
			// aapt resource value: 0x7f02013f
			public const int pdd_23_06 = 2130837823;
			
			// aapt resource value: 0x7f020140
			public const int pdd_23_08 = 2130837824;
			
			// aapt resource value: 0x7f020141
			public const int pdd_23_09 = 2130837825;
			
			// aapt resource value: 0x7f020142
			public const int pdd_23_10 = 2130837826;
			
			// aapt resource value: 0x7f020143
			public const int pdd_23_11 = 2130837827;
			
			// aapt resource value: 0x7f020144
			public const int pdd_23_12 = 2130837828;
			
			// aapt resource value: 0x7f020145
			public const int pdd_23_13 = 2130837829;
			
			// aapt resource value: 0x7f020146
			public const int pdd_23_14 = 2130837830;
			
			// aapt resource value: 0x7f020147
			public const int pdd_23_15 = 2130837831;
			
			// aapt resource value: 0x7f020148
			public const int pdd_23_16 = 2130837832;
			
			// aapt resource value: 0x7f020149
			public const int pdd_24_01 = 2130837833;
			
			// aapt resource value: 0x7f02014a
			public const int pdd_24_02 = 2130837834;
			
			// aapt resource value: 0x7f02014b
			public const int pdd_24_03 = 2130837835;
			
			// aapt resource value: 0x7f02014c
			public const int pdd_24_04 = 2130837836;
			
			// aapt resource value: 0x7f02014d
			public const int pdd_24_05 = 2130837837;
			
			// aapt resource value: 0x7f02014e
			public const int pdd_24_07 = 2130837838;
			
			// aapt resource value: 0x7f02014f
			public const int pdd_24_08 = 2130837839;
			
			// aapt resource value: 0x7f020150
			public const int pdd_24_09 = 2130837840;
			
			// aapt resource value: 0x7f020151
			public const int pdd_24_10 = 2130837841;
			
			// aapt resource value: 0x7f020152
			public const int pdd_24_11 = 2130837842;
			
			// aapt resource value: 0x7f020153
			public const int pdd_24_12 = 2130837843;
			
			// aapt resource value: 0x7f020154
			public const int pdd_24_13 = 2130837844;
			
			// aapt resource value: 0x7f020155
			public const int pdd_24_14 = 2130837845;
			
			// aapt resource value: 0x7f020156
			public const int pdd_24_15 = 2130837846;
			
			// aapt resource value: 0x7f020157
			public const int pdd_24_16 = 2130837847;
			
			// aapt resource value: 0x7f020158
			public const int pdd_25_01 = 2130837848;
			
			// aapt resource value: 0x7f020159
			public const int pdd_25_02 = 2130837849;
			
			// aapt resource value: 0x7f02015a
			public const int pdd_25_03 = 2130837850;
			
			// aapt resource value: 0x7f02015b
			public const int pdd_25_04 = 2130837851;
			
			// aapt resource value: 0x7f02015c
			public const int pdd_25_05 = 2130837852;
			
			// aapt resource value: 0x7f02015d
			public const int pdd_25_06 = 2130837853;
			
			// aapt resource value: 0x7f02015e
			public const int pdd_25_07 = 2130837854;
			
			// aapt resource value: 0x7f02015f
			public const int pdd_25_08 = 2130837855;
			
			// aapt resource value: 0x7f020160
			public const int pdd_25_09 = 2130837856;
			
			// aapt resource value: 0x7f020161
			public const int pdd_25_10 = 2130837857;
			
			// aapt resource value: 0x7f020162
			public const int pdd_25_11 = 2130837858;
			
			// aapt resource value: 0x7f020163
			public const int pdd_25_12 = 2130837859;
			
			// aapt resource value: 0x7f020164
			public const int pdd_25_14 = 2130837860;
			
			// aapt resource value: 0x7f020165
			public const int pdd_25_15 = 2130837861;
			
			// aapt resource value: 0x7f020166
			public const int pdd_25_16 = 2130837862;
			
			// aapt resource value: 0x7f020167
			public const int pdd_26_01 = 2130837863;
			
			// aapt resource value: 0x7f020168
			public const int pdd_26_02 = 2130837864;
			
			// aapt resource value: 0x7f020169
			public const int pdd_26_03 = 2130837865;
			
			// aapt resource value: 0x7f02016a
			public const int pdd_26_04 = 2130837866;
			
			// aapt resource value: 0x7f02016b
			public const int pdd_26_05 = 2130837867;
			
			// aapt resource value: 0x7f02016c
			public const int pdd_26_07 = 2130837868;
			
			// aapt resource value: 0x7f02016d
			public const int pdd_26_08 = 2130837869;
			
			// aapt resource value: 0x7f02016e
			public const int pdd_26_09 = 2130837870;
			
			// aapt resource value: 0x7f02016f
			public const int pdd_26_10 = 2130837871;
			
			// aapt resource value: 0x7f020170
			public const int pdd_26_12 = 2130837872;
			
			// aapt resource value: 0x7f020171
			public const int pdd_26_13 = 2130837873;
			
			// aapt resource value: 0x7f020172
			public const int pdd_26_14 = 2130837874;
			
			// aapt resource value: 0x7f020173
			public const int pdd_26_15 = 2130837875;
			
			// aapt resource value: 0x7f020174
			public const int pdd_26_17 = 2130837876;
			
			// aapt resource value: 0x7f020175
			public const int pdd_27_02 = 2130837877;
			
			// aapt resource value: 0x7f020176
			public const int pdd_27_03 = 2130837878;
			
			// aapt resource value: 0x7f020177
			public const int pdd_27_04 = 2130837879;
			
			// aapt resource value: 0x7f020178
			public const int pdd_27_05 = 2130837880;
			
			// aapt resource value: 0x7f020179
			public const int pdd_27_07 = 2130837881;
			
			// aapt resource value: 0x7f02017a
			public const int pdd_27_08 = 2130837882;
			
			// aapt resource value: 0x7f02017b
			public const int pdd_27_09 = 2130837883;
			
			// aapt resource value: 0x7f02017c
			public const int pdd_27_10 = 2130837884;
			
			// aapt resource value: 0x7f02017d
			public const int pdd_27_12 = 2130837885;
			
			// aapt resource value: 0x7f02017e
			public const int pdd_27_13 = 2130837886;
			
			// aapt resource value: 0x7f02017f
			public const int pdd_27_14 = 2130837887;
			
			// aapt resource value: 0x7f020180
			public const int pdd_27_15 = 2130837888;
			
			// aapt resource value: 0x7f020181
			public const int pdd_27_16 = 2130837889;
			
			// aapt resource value: 0x7f020182
			public const int pdd_28_02 = 2130837890;
			
			// aapt resource value: 0x7f020183
			public const int pdd_28_03 = 2130837891;
			
			// aapt resource value: 0x7f020184
			public const int pdd_28_04 = 2130837892;
			
			// aapt resource value: 0x7f020185
			public const int pdd_28_05 = 2130837893;
			
			// aapt resource value: 0x7f020186
			public const int pdd_28_06 = 2130837894;
			
			// aapt resource value: 0x7f020187
			public const int pdd_28_08 = 2130837895;
			
			// aapt resource value: 0x7f020188
			public const int pdd_28_09 = 2130837896;
			
			// aapt resource value: 0x7f020189
			public const int pdd_28_10 = 2130837897;
			
			// aapt resource value: 0x7f02018a
			public const int pdd_28_11 = 2130837898;
			
			// aapt resource value: 0x7f02018b
			public const int pdd_28_12 = 2130837899;
			
			// aapt resource value: 0x7f02018c
			public const int pdd_28_13 = 2130837900;
			
			// aapt resource value: 0x7f02018d
			public const int pdd_28_14 = 2130837901;
			
			// aapt resource value: 0x7f02018e
			public const int pdd_28_15 = 2130837902;
			
			// aapt resource value: 0x7f02018f
			public const int pdd_28_16 = 2130837903;
			
			// aapt resource value: 0x7f020190
			public const int pdd_29_02 = 2130837904;
			
			// aapt resource value: 0x7f020191
			public const int pdd_29_03 = 2130837905;
			
			// aapt resource value: 0x7f020192
			public const int pdd_29_04 = 2130837906;
			
			// aapt resource value: 0x7f020193
			public const int pdd_29_05 = 2130837907;
			
			// aapt resource value: 0x7f020194
			public const int pdd_29_06 = 2130837908;
			
			// aapt resource value: 0x7f020195
			public const int pdd_29_08 = 2130837909;
			
			// aapt resource value: 0x7f020196
			public const int pdd_29_09 = 2130837910;
			
			// aapt resource value: 0x7f020197
			public const int pdd_29_10 = 2130837911;
			
			// aapt resource value: 0x7f020198
			public const int pdd_29_11 = 2130837912;
			
			// aapt resource value: 0x7f020199
			public const int pdd_29_12 = 2130837913;
			
			// aapt resource value: 0x7f02019a
			public const int pdd_29_13 = 2130837914;
			
			// aapt resource value: 0x7f02019b
			public const int pdd_29_14 = 2130837915;
			
			// aapt resource value: 0x7f02019c
			public const int pdd_29_15 = 2130837916;
			
			// aapt resource value: 0x7f02019d
			public const int pdd_29_16 = 2130837917;
			
			// aapt resource value: 0x7f02019e
			public const int pdd_30_01 = 2130837918;
			
			// aapt resource value: 0x7f02019f
			public const int pdd_30_02 = 2130837919;
			
			// aapt resource value: 0x7f0201a0
			public const int pdd_30_03 = 2130837920;
			
			// aapt resource value: 0x7f0201a1
			public const int pdd_30_04 = 2130837921;
			
			// aapt resource value: 0x7f0201a2
			public const int pdd_30_05 = 2130837922;
			
			// aapt resource value: 0x7f0201a3
			public const int pdd_30_06 = 2130837923;
			
			// aapt resource value: 0x7f0201a4
			public const int pdd_30_08 = 2130837924;
			
			// aapt resource value: 0x7f0201a5
			public const int pdd_30_09 = 2130837925;
			
			// aapt resource value: 0x7f0201a6
			public const int pdd_30_10 = 2130837926;
			
			// aapt resource value: 0x7f0201a7
			public const int pdd_30_12 = 2130837927;
			
			// aapt resource value: 0x7f0201a8
			public const int pdd_30_13 = 2130837928;
			
			// aapt resource value: 0x7f0201a9
			public const int pdd_30_14 = 2130837929;
			
			// aapt resource value: 0x7f0201aa
			public const int pdd_30_15 = 2130837930;
			
			// aapt resource value: 0x7f0201ab
			public const int pdd_30_19 = 2130837931;
			
			// aapt resource value: 0x7f0201ac
			public const int pdd_31_01 = 2130837932;
			
			// aapt resource value: 0x7f0201ad
			public const int pdd_31_02 = 2130837933;
			
			// aapt resource value: 0x7f0201ae
			public const int pdd_31_03 = 2130837934;
			
			// aapt resource value: 0x7f0201af
			public const int pdd_31_04 = 2130837935;
			
			// aapt resource value: 0x7f0201b0
			public const int pdd_31_06 = 2130837936;
			
			// aapt resource value: 0x7f0201b1
			public const int pdd_31_07 = 2130837937;
			
			// aapt resource value: 0x7f0201b2
			public const int pdd_31_08 = 2130837938;
			
			// aapt resource value: 0x7f0201b3
			public const int pdd_31_09 = 2130837939;
			
			// aapt resource value: 0x7f0201b4
			public const int pdd_31_10 = 2130837940;
			
			// aapt resource value: 0x7f0201b5
			public const int pdd_31_11 = 2130837941;
			
			// aapt resource value: 0x7f0201b6
			public const int pdd_31_12 = 2130837942;
			
			// aapt resource value: 0x7f0201b7
			public const int pdd_31_13 = 2130837943;
			
			// aapt resource value: 0x7f0201b8
			public const int pdd_31_14 = 2130837944;
			
			// aapt resource value: 0x7f0201b9
			public const int pdd_31_15 = 2130837945;
			
			// aapt resource value: 0x7f0201ba
			public const int pdd_31_16 = 2130837946;
			
			// aapt resource value: 0x7f0201bb
			public const int pdd_32_02 = 2130837947;
			
			// aapt resource value: 0x7f0201bc
			public const int pdd_32_03 = 2130837948;
			
			// aapt resource value: 0x7f0201bd
			public const int pdd_32_04 = 2130837949;
			
			// aapt resource value: 0x7f0201be
			public const int pdd_32_05 = 2130837950;
			
			// aapt resource value: 0x7f0201bf
			public const int pdd_32_06 = 2130837951;
			
			// aapt resource value: 0x7f0201c0
			public const int pdd_32_07 = 2130837952;
			
			// aapt resource value: 0x7f0201c1
			public const int pdd_32_09 = 2130837953;
			
			// aapt resource value: 0x7f0201c2
			public const int pdd_32_10 = 2130837954;
			
			// aapt resource value: 0x7f0201c3
			public const int pdd_32_12 = 2130837955;
			
			// aapt resource value: 0x7f0201c4
			public const int pdd_32_13 = 2130837956;
			
			// aapt resource value: 0x7f0201c5
			public const int pdd_32_14 = 2130837957;
			
			// aapt resource value: 0x7f0201c6
			public const int pdd_32_15 = 2130837958;
			
			// aapt resource value: 0x7f0201c7
			public const int pdd_32_19 = 2130837959;
			
			// aapt resource value: 0x7f0201c8
			public const int pdd_33_01 = 2130837960;
			
			// aapt resource value: 0x7f0201c9
			public const int pdd_33_02 = 2130837961;
			
			// aapt resource value: 0x7f0201ca
			public const int pdd_33_03 = 2130837962;
			
			// aapt resource value: 0x7f0201cb
			public const int pdd_33_04 = 2130837963;
			
			// aapt resource value: 0x7f0201cc
			public const int pdd_33_05 = 2130837964;
			
			// aapt resource value: 0x7f0201cd
			public const int pdd_33_06 = 2130837965;
			
			// aapt resource value: 0x7f0201ce
			public const int pdd_33_08 = 2130837966;
			
			// aapt resource value: 0x7f0201cf
			public const int pdd_33_09 = 2130837967;
			
			// aapt resource value: 0x7f0201d0
			public const int pdd_33_10 = 2130837968;
			
			// aapt resource value: 0x7f0201d1
			public const int pdd_33_11 = 2130837969;
			
			// aapt resource value: 0x7f0201d2
			public const int pdd_33_12 = 2130837970;
			
			// aapt resource value: 0x7f0201d3
			public const int pdd_33_13 = 2130837971;
			
			// aapt resource value: 0x7f0201d4
			public const int pdd_33_14 = 2130837972;
			
			// aapt resource value: 0x7f0201d5
			public const int pdd_33_15 = 2130837973;
			
			// aapt resource value: 0x7f0201d6
			public const int pdd_33_16 = 2130837974;
			
			// aapt resource value: 0x7f0201d7
			public const int pdd_34_01 = 2130837975;
			
			// aapt resource value: 0x7f0201d8
			public const int pdd_34_02 = 2130837976;
			
			// aapt resource value: 0x7f0201d9
			public const int pdd_34_03 = 2130837977;
			
			// aapt resource value: 0x7f0201da
			public const int pdd_34_04 = 2130837978;
			
			// aapt resource value: 0x7f0201db
			public const int pdd_34_05 = 2130837979;
			
			// aapt resource value: 0x7f0201dc
			public const int pdd_34_06 = 2130837980;
			
			// aapt resource value: 0x7f0201dd
			public const int pdd_34_07 = 2130837981;
			
			// aapt resource value: 0x7f0201de
			public const int pdd_34_08 = 2130837982;
			
			// aapt resource value: 0x7f0201df
			public const int pdd_34_09 = 2130837983;
			
			// aapt resource value: 0x7f0201e0
			public const int pdd_34_10 = 2130837984;
			
			// aapt resource value: 0x7f0201e1
			public const int pdd_34_11 = 2130837985;
			
			// aapt resource value: 0x7f0201e2
			public const int pdd_34_12 = 2130837986;
			
			// aapt resource value: 0x7f0201e3
			public const int pdd_34_13 = 2130837987;
			
			// aapt resource value: 0x7f0201e4
			public const int pdd_34_14 = 2130837988;
			
			// aapt resource value: 0x7f0201e5
			public const int pdd_34_15 = 2130837989;
			
			// aapt resource value: 0x7f0201e6
			public const int pdd_34_19 = 2130837990;
			
			// aapt resource value: 0x7f0201e7
			public const int pdd_35_02 = 2130837991;
			
			// aapt resource value: 0x7f0201e8
			public const int pdd_35_03 = 2130837992;
			
			// aapt resource value: 0x7f0201e9
			public const int pdd_35_04 = 2130837993;
			
			// aapt resource value: 0x7f0201ea
			public const int pdd_35_05 = 2130837994;
			
			// aapt resource value: 0x7f0201eb
			public const int pdd_35_07 = 2130837995;
			
			// aapt resource value: 0x7f0201ec
			public const int pdd_35_08 = 2130837996;
			
			// aapt resource value: 0x7f0201ed
			public const int pdd_35_09 = 2130837997;
			
			// aapt resource value: 0x7f0201ee
			public const int pdd_35_10 = 2130837998;
			
			// aapt resource value: 0x7f0201ef
			public const int pdd_35_11 = 2130837999;
			
			// aapt resource value: 0x7f0201f0
			public const int pdd_35_12 = 2130838000;
			
			// aapt resource value: 0x7f0201f1
			public const int pdd_35_13 = 2130838001;
			
			// aapt resource value: 0x7f0201f2
			public const int pdd_35_14 = 2130838002;
			
			// aapt resource value: 0x7f0201f3
			public const int pdd_35_15 = 2130838003;
			
			// aapt resource value: 0x7f0201f4
			public const int pdd_36_02 = 2130838004;
			
			// aapt resource value: 0x7f0201f5
			public const int pdd_36_03 = 2130838005;
			
			// aapt resource value: 0x7f0201f6
			public const int pdd_36_04 = 2130838006;
			
			// aapt resource value: 0x7f0201f7
			public const int pdd_36_05 = 2130838007;
			
			// aapt resource value: 0x7f0201f8
			public const int pdd_36_06 = 2130838008;
			
			// aapt resource value: 0x7f0201f9
			public const int pdd_36_07 = 2130838009;
			
			// aapt resource value: 0x7f0201fa
			public const int pdd_36_08 = 2130838010;
			
			// aapt resource value: 0x7f0201fb
			public const int pdd_36_09 = 2130838011;
			
			// aapt resource value: 0x7f0201fc
			public const int pdd_36_12 = 2130838012;
			
			// aapt resource value: 0x7f0201fd
			public const int pdd_36_13 = 2130838013;
			
			// aapt resource value: 0x7f0201fe
			public const int pdd_36_14 = 2130838014;
			
			// aapt resource value: 0x7f0201ff
			public const int pdd_36_15 = 2130838015;
			
			// aapt resource value: 0x7f020200
			public const int pdd_36_16 = 2130838016;
			
			// aapt resource value: 0x7f020201
			public const int pdd_37_02 = 2130838017;
			
			// aapt resource value: 0x7f020202
			public const int pdd_37_03 = 2130838018;
			
			// aapt resource value: 0x7f020203
			public const int pdd_37_04 = 2130838019;
			
			// aapt resource value: 0x7f020204
			public const int pdd_37_05 = 2130838020;
			
			// aapt resource value: 0x7f020205
			public const int pdd_37_06 = 2130838021;
			
			// aapt resource value: 0x7f020206
			public const int pdd_37_07 = 2130838022;
			
			// aapt resource value: 0x7f020207
			public const int pdd_37_08 = 2130838023;
			
			// aapt resource value: 0x7f020208
			public const int pdd_37_09 = 2130838024;
			
			// aapt resource value: 0x7f020209
			public const int pdd_37_11 = 2130838025;
			
			// aapt resource value: 0x7f02020a
			public const int pdd_37_12 = 2130838026;
			
			// aapt resource value: 0x7f02020b
			public const int pdd_37_13 = 2130838027;
			
			// aapt resource value: 0x7f02020c
			public const int pdd_37_14 = 2130838028;
			
			// aapt resource value: 0x7f02020d
			public const int pdd_37_15 = 2130838029;
			
			// aapt resource value: 0x7f02020e
			public const int pdd_37_17 = 2130838030;
			
			// aapt resource value: 0x7f02020f
			public const int pdd_38_01 = 2130838031;
			
			// aapt resource value: 0x7f020210
			public const int pdd_38_02 = 2130838032;
			
			// aapt resource value: 0x7f020211
			public const int pdd_38_03 = 2130838033;
			
			// aapt resource value: 0x7f020212
			public const int pdd_38_04 = 2130838034;
			
			// aapt resource value: 0x7f020213
			public const int pdd_38_05 = 2130838035;
			
			// aapt resource value: 0x7f020214
			public const int pdd_38_07 = 2130838036;
			
			// aapt resource value: 0x7f020215
			public const int pdd_38_08 = 2130838037;
			
			// aapt resource value: 0x7f020216
			public const int pdd_38_09 = 2130838038;
			
			// aapt resource value: 0x7f020217
			public const int pdd_38_10 = 2130838039;
			
			// aapt resource value: 0x7f020218
			public const int pdd_38_11 = 2130838040;
			
			// aapt resource value: 0x7f020219
			public const int pdd_38_12 = 2130838041;
			
			// aapt resource value: 0x7f02021a
			public const int pdd_38_13 = 2130838042;
			
			// aapt resource value: 0x7f02021b
			public const int pdd_38_14 = 2130838043;
			
			// aapt resource value: 0x7f02021c
			public const int pdd_38_15 = 2130838044;
			
			// aapt resource value: 0x7f02021d
			public const int pdd_39_02 = 2130838045;
			
			// aapt resource value: 0x7f02021e
			public const int pdd_39_03 = 2130838046;
			
			// aapt resource value: 0x7f02021f
			public const int pdd_39_04 = 2130838047;
			
			// aapt resource value: 0x7f020220
			public const int pdd_39_05 = 2130838048;
			
			// aapt resource value: 0x7f020221
			public const int pdd_39_06 = 2130838049;
			
			// aapt resource value: 0x7f020222
			public const int pdd_39_08 = 2130838050;
			
			// aapt resource value: 0x7f020223
			public const int pdd_39_09 = 2130838051;
			
			// aapt resource value: 0x7f020224
			public const int pdd_39_10 = 2130838052;
			
			// aapt resource value: 0x7f020225
			public const int pdd_39_11 = 2130838053;
			
			// aapt resource value: 0x7f020226
			public const int pdd_39_12 = 2130838054;
			
			// aapt resource value: 0x7f020227
			public const int pdd_39_13 = 2130838055;
			
			// aapt resource value: 0x7f020228
			public const int pdd_39_14 = 2130838056;
			
			// aapt resource value: 0x7f020229
			public const int pdd_39_15 = 2130838057;
			
			// aapt resource value: 0x7f02022a
			public const int pdd_39_16 = 2130838058;
			
			// aapt resource value: 0x7f02022b
			public const int pdd_40_02 = 2130838059;
			
			// aapt resource value: 0x7f02022c
			public const int pdd_40_03 = 2130838060;
			
			// aapt resource value: 0x7f02022d
			public const int pdd_40_04 = 2130838061;
			
			// aapt resource value: 0x7f02022e
			public const int pdd_40_05 = 2130838062;
			
			// aapt resource value: 0x7f02022f
			public const int pdd_40_06 = 2130838063;
			
			// aapt resource value: 0x7f020230
			public const int pdd_40_07 = 2130838064;
			
			// aapt resource value: 0x7f020231
			public const int pdd_40_08 = 2130838065;
			
			// aapt resource value: 0x7f020232
			public const int pdd_40_09 = 2130838066;
			
			// aapt resource value: 0x7f020233
			public const int pdd_40_10 = 2130838067;
			
			// aapt resource value: 0x7f020234
			public const int pdd_40_11 = 2130838068;
			
			// aapt resource value: 0x7f020235
			public const int pdd_40_12 = 2130838069;
			
			// aapt resource value: 0x7f020236
			public const int pdd_40_13 = 2130838070;
			
			// aapt resource value: 0x7f020237
			public const int pdd_40_14 = 2130838071;
			
			// aapt resource value: 0x7f020238
			public const int pdd_40_15 = 2130838072;
			
			// aapt resource value: 0x7f020239
			public const int pdd_40_16 = 2130838073;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050001
			public const int buttonDontKnow = 2131034113;
			
			// aapt resource value: 0x7f050005
			public const int imageView1 = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int myButton = 2131034118;
			
			// aapt resource value: 0x7f050003
			public const int progressBar = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int textViewHint = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int textViewProgress = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int textViewQuestion = 2131034116;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ChoiceTextItem = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Footer = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Header = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
